package to_words

import (
	"fmt"
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIth(t *testing.T) {
	tests := []struct {
		n   int
		exp string
	}{
		{n: 0, exp: "0th"},
		{n: 1, exp: "1st"},
		{n: 2, exp: "2nd"},
		{n: 3, exp: "3rd"},
		{n: 4, exp: "4th"},
		{n: 5, exp: "5th"},
		{n: 6, exp: "6th"},
		{n: 7, exp: "7th"},
		{n: 8, exp: "8th"},
		{n: 9, exp: "9th"},
		{n: 10, exp: "10th"},
		{n: 11, exp: "11th"},
		{n: 12, exp: "12th"},
		{n: 13, exp: "13th"},
		{n: 14, exp: "14th"},
		{n: 15, exp: "15th"},
		{n: 16, exp: "16th"},
		{n: 17, exp: "17th"},
		{n: 18, exp: "18th"},
		{n: 19, exp: "19th"},
		{n: 20, exp: "20th"},
		{n: 21, exp: "21st"},
		{n: 22, exp: "22nd"},
		{n: 23, exp: "23rd"},
		{n: 24, exp: "24th"},
		{n: 25, exp: "25th"},
		{n: 26, exp: "26th"},
		{n: 27, exp: "27th"},
		{n: 28, exp: "28th"},
		{n: 29, exp: "29th"},
		{n: 30, exp: "30th"},
		{n: 31, exp: "31st"},
		{n: 32, exp: "32nd"},
		{n: 33, exp: "33rd"},
		{n: 34, exp: "34th"},
		{n: 35, exp: "35th"},
		{n: 36, exp: "36th"},
		{n: 37, exp: "37th"},
		{n: 38, exp: "38th"},
		{n: 39, exp: "39th"},
		{n: 40, exp: "40th"},
		{n: 41, exp: "41st"},
		{n: 42, exp: "42nd"},
		{n: 43, exp: "43rd"},
		{n: 44, exp: "44th"},
		{n: 45, exp: "45th"},
		{n: 46, exp: "46th"},
		{n: 47, exp: "47th"},
		{n: 48, exp: "48th"},
		{n: 49, exp: "49th"},
		{n: 50, exp: "50th"},
		{n: 51, exp: "51st"},
		{n: 52, exp: "52nd"},
		{n: 53, exp: "53rd"},
		{n: 54, exp: "54th"},
		{n: 55, exp: "55th"},
		{n: 56, exp: "56th"},
		{n: 57, exp: "57th"},
		{n: 58, exp: "58th"},
		{n: 59, exp: "59th"},
		{n: 60, exp: "60th"},
		{n: 61, exp: "61st"},
		{n: 62, exp: "62nd"},
		{n: 63, exp: "63rd"},
		{n: 64, exp: "64th"},
		{n: 65, exp: "65th"},
		{n: 66, exp: "66th"},
		{n: 67, exp: "67th"},
		{n: 68, exp: "68th"},
		{n: 69, exp: "69th"},
		{n: 70, exp: "70th"},
		{n: 71, exp: "71st"},
		{n: 72, exp: "72nd"},
		{n: 73, exp: "73rd"},
		{n: 74, exp: "74th"},
		{n: 75, exp: "75th"},
		{n: 76, exp: "76th"},
		{n: 77, exp: "77th"},
		{n: 78, exp: "78th"},
		{n: 79, exp: "79th"},
		{n: 80, exp: "80th"},
		{n: 81, exp: "81st"},
		{n: 82, exp: "82nd"},
		{n: 83, exp: "83rd"},
		{n: 84, exp: "84th"},
		{n: 85, exp: "85th"},
		{n: 86, exp: "86th"},
		{n: 87, exp: "87th"},
		{n: 88, exp: "88th"},
		{n: 89, exp: "89th"},
		{n: 90, exp: "90th"},
		{n: 91, exp: "91st"},
		{n: 92, exp: "92nd"},
		{n: 93, exp: "93rd"},
		{n: 94, exp: "94th"},
		{n: 95, exp: "95th"},
		{n: 96, exp: "96th"},
		{n: 97, exp: "97th"},
		{n: 98, exp: "98th"},
		{n: 99, exp: "99th"},
		{n: 100, exp: "100th"},
		{n: 101, exp: "101st"},
		{n: 102, exp: "102nd"},
		{n: 103, exp: "103rd"},
		{n: 104, exp: "104th"},
		{n: 105, exp: "105th"},
		{n: 106, exp: "106th"},
		{n: 107, exp: "107th"},
		{n: 108, exp: "108th"},
		{n: 109, exp: "109th"},
		{n: 110, exp: "110th"},
		{n: 111, exp: "111th"},
		{n: 112, exp: "112th"},
		{n: 113, exp: "113th"},
		{n: 114, exp: "114th"},
		{n: 115, exp: "115th"},
		{n: 116, exp: "116th"},
		{n: 117, exp: "117th"},
		{n: 118, exp: "118th"},
		{n: 119, exp: "119th"},
		{n: 120, exp: "120th"},
	}

	for _, tc := range tests {
		t.Run(strconv.Itoa(tc.n), func(t *testing.T) {
			var act string
			testFunc := func() {
				act = Ith(tc.n)
			}
			require.NotPanics(t, testFunc, "Ith(%d)", tc.n)
			assert.Equal(t, tc.exp, act, "Ith(%d) result", tc.n)
		})
	}
}

func TestIthWords(t *testing.T) {
	tests := []struct {
		num int
		exp string
	}{
		{num: 0, exp: "zeroth"},
		{num: 1, exp: "first"},
		{num: -1, exp: "negative first"},
		{num: 2, exp: "second"},
		{num: -2, exp: "negative second"},
		{num: 3, exp: "third"},
		{num: -3, exp: "negative third"},
		{num: 4, exp: "fourth"},
		{num: -4, exp: "negative fourth"},
		{num: 5, exp: "fifth"},
		{num: -5, exp: "negative fifth"},
		{num: 6, exp: "sixth"},
		{num: -6, exp: "negative sixth"},
		{num: 7, exp: "seventh"},
		{num: -7, exp: "negative seventh"},
		{num: 8, exp: "eighth"},
		{num: -8, exp: "negative eighth"},
		{num: 9, exp: "ninth"},
		{num: -9, exp: "negative ninth"},
		{num: 10, exp: "tenth"},
		{num: -10, exp: "negative tenth"},
		{num: 11, exp: "eleventh"},
		{num: -11, exp: "negative eleventh"},
		{num: 12, exp: "twelfth"},
		{num: -12, exp: "negative twelfth"},
		{num: 13, exp: "thirteenth"},
		{num: -13, exp: "negative thirteenth"},
		{num: 14, exp: "fourteenth"},
		{num: -14, exp: "negative fourteenth"},
		{num: 15, exp: "fifteenth"},
		{num: -15, exp: "negative fifteenth"},
		{num: 16, exp: "sixteenth"},
		{num: -16, exp: "negative sixteenth"},
		{num: 17, exp: "seventeenth"},
		{num: -17, exp: "negative seventeenth"},
		{num: 18, exp: "eighteenth"},
		{num: -18, exp: "negative eighteenth"},
		{num: 19, exp: "nineteenth"},
		{num: -19, exp: "negative nineteenth"},
		{num: 20, exp: "twentieth"},
		{num: -20, exp: "negative twentieth"},
		{num: 21, exp: "twenty-first"},
		{num: -21, exp: "negative twenty-first"},
		{num: 22, exp: "twenty-second"},
		{num: -22, exp: "negative twenty-second"},
		{num: 23, exp: "twenty-third"},
		{num: -23, exp: "negative twenty-third"},
		{num: 24, exp: "twenty-fourth"},
		{num: -24, exp: "negative twenty-fourth"},
		{num: 25, exp: "twenty-fifth"},
		{num: -25, exp: "negative twenty-fifth"},
		{num: 26, exp: "twenty-sixth"},
		{num: -26, exp: "negative twenty-sixth"},
		{num: 27, exp: "twenty-seventh"},
		{num: -27, exp: "negative twenty-seventh"},
		{num: 28, exp: "twenty-eighth"},
		{num: -28, exp: "negative twenty-eighth"},
		{num: 29, exp: "twenty-ninth"},
		{num: -29, exp: "negative twenty-ninth"},
		{num: 30, exp: "thirtieth"},
		{num: -30, exp: "negative thirtieth"},
		{num: 31, exp: "thirty-first"},
		{num: -31, exp: "negative thirty-first"},
		{num: 32, exp: "thirty-second"},
		{num: -32, exp: "negative thirty-second"},
		{num: 33, exp: "thirty-third"},
		{num: -33, exp: "negative thirty-third"},
		{num: 34, exp: "thirty-fourth"},
		{num: -34, exp: "negative thirty-fourth"},
		{num: 35, exp: "thirty-fifth"},
		{num: -35, exp: "negative thirty-fifth"},
		{num: 36, exp: "thirty-sixth"},
		{num: -36, exp: "negative thirty-sixth"},
		{num: 37, exp: "thirty-seventh"},
		{num: -37, exp: "negative thirty-seventh"},
		{num: 38, exp: "thirty-eighth"},
		{num: -38, exp: "negative thirty-eighth"},
		{num: 39, exp: "thirty-ninth"},
		{num: -39, exp: "negative thirty-ninth"},
		{num: 40, exp: "fortieth"},
		{num: -40, exp: "negative fortieth"},
		{num: 41, exp: "forty-first"},
		{num: -41, exp: "negative forty-first"},
		{num: 42, exp: "forty-second"},
		{num: -42, exp: "negative forty-second"},
		{num: 43, exp: "forty-third"},
		{num: -43, exp: "negative forty-third"},
		{num: 44, exp: "forty-fourth"},
		{num: -44, exp: "negative forty-fourth"},
		{num: 45, exp: "forty-fifth"},
		{num: -45, exp: "negative forty-fifth"},
		{num: 46, exp: "forty-sixth"},
		{num: -46, exp: "negative forty-sixth"},
		{num: 47, exp: "forty-seventh"},
		{num: -47, exp: "negative forty-seventh"},
		{num: 48, exp: "forty-eighth"},
		{num: -48, exp: "negative forty-eighth"},
		{num: 49, exp: "forty-ninth"},
		{num: -49, exp: "negative forty-ninth"},
		{num: 50, exp: "fiftieth"},
		{num: -50, exp: "negative fiftieth"},
		{num: 51, exp: "fifty-first"},
		{num: -51, exp: "negative fifty-first"},
		{num: 52, exp: "fifty-second"},
		{num: -52, exp: "negative fifty-second"},
		{num: 53, exp: "fifty-third"},
		{num: -53, exp: "negative fifty-third"},
		{num: 54, exp: "fifty-fourth"},
		{num: -54, exp: "negative fifty-fourth"},
		{num: 55, exp: "fifty-fifth"},
		{num: -55, exp: "negative fifty-fifth"},
		{num: 56, exp: "fifty-sixth"},
		{num: -56, exp: "negative fifty-sixth"},
		{num: 57, exp: "fifty-seventh"},
		{num: -57, exp: "negative fifty-seventh"},
		{num: 58, exp: "fifty-eighth"},
		{num: -58, exp: "negative fifty-eighth"},
		{num: 59, exp: "fifty-ninth"},
		{num: -59, exp: "negative fifty-ninth"},
		{num: 60, exp: "sixtieth"},
		{num: -60, exp: "negative sixtieth"},
		{num: 61, exp: "sixty-first"},
		{num: -61, exp: "negative sixty-first"},
		{num: 62, exp: "sixty-second"},
		{num: -62, exp: "negative sixty-second"},
		{num: 63, exp: "sixty-third"},
		{num: -63, exp: "negative sixty-third"},
		{num: 64, exp: "sixty-fourth"},
		{num: -64, exp: "negative sixty-fourth"},
		{num: 65, exp: "sixty-fifth"},
		{num: -65, exp: "negative sixty-fifth"},
		{num: 66, exp: "sixty-sixth"},
		{num: -66, exp: "negative sixty-sixth"},
		{num: 67, exp: "sixty-seventh"},
		{num: -67, exp: "negative sixty-seventh"},
		{num: 68, exp: "sixty-eighth"},
		{num: -68, exp: "negative sixty-eighth"},
		{num: 69, exp: "sixty-ninth"},
		{num: -69, exp: "negative sixty-ninth"},
		{num: 70, exp: "seventieth"},
		{num: -70, exp: "negative seventieth"},
		{num: 71, exp: "seventy-first"},
		{num: -71, exp: "negative seventy-first"},
		{num: 72, exp: "seventy-second"},
		{num: -72, exp: "negative seventy-second"},
		{num: 73, exp: "seventy-third"},
		{num: -73, exp: "negative seventy-third"},
		{num: 74, exp: "seventy-fourth"},
		{num: -74, exp: "negative seventy-fourth"},
		{num: 75, exp: "seventy-fifth"},
		{num: -75, exp: "negative seventy-fifth"},
		{num: 76, exp: "seventy-sixth"},
		{num: -76, exp: "negative seventy-sixth"},
		{num: 77, exp: "seventy-seventh"},
		{num: -77, exp: "negative seventy-seventh"},
		{num: 78, exp: "seventy-eighth"},
		{num: -78, exp: "negative seventy-eighth"},
		{num: 79, exp: "seventy-ninth"},
		{num: -79, exp: "negative seventy-ninth"},
		{num: 80, exp: "eightieth"},
		{num: -80, exp: "negative eightieth"},
		{num: 81, exp: "eighty-first"},
		{num: -81, exp: "negative eighty-first"},
		{num: 82, exp: "eighty-second"},
		{num: -82, exp: "negative eighty-second"},
		{num: 83, exp: "eighty-third"},
		{num: -83, exp: "negative eighty-third"},
		{num: 84, exp: "eighty-fourth"},
		{num: -84, exp: "negative eighty-fourth"},
		{num: 85, exp: "eighty-fifth"},
		{num: -85, exp: "negative eighty-fifth"},
		{num: 86, exp: "eighty-sixth"},
		{num: -86, exp: "negative eighty-sixth"},
		{num: 87, exp: "eighty-seventh"},
		{num: -87, exp: "negative eighty-seventh"},
		{num: 88, exp: "eighty-eighth"},
		{num: -88, exp: "negative eighty-eighth"},
		{num: 89, exp: "eighty-ninth"},
		{num: -89, exp: "negative eighty-ninth"},
		{num: 90, exp: "ninetieth"},
		{num: -90, exp: "negative ninetieth"},
		{num: 91, exp: "ninety-first"},
		{num: -91, exp: "negative ninety-first"},
		{num: 92, exp: "ninety-second"},
		{num: -92, exp: "negative ninety-second"},
		{num: 93, exp: "ninety-third"},
		{num: -93, exp: "negative ninety-third"},
		{num: 94, exp: "ninety-fourth"},
		{num: -94, exp: "negative ninety-fourth"},
		{num: 95, exp: "ninety-fifth"},
		{num: -95, exp: "negative ninety-fifth"},
		{num: 96, exp: "ninety-sixth"},
		{num: -96, exp: "negative ninety-sixth"},
		{num: 97, exp: "ninety-seventh"},
		{num: -97, exp: "negative ninety-seventh"},
		{num: 98, exp: "ninety-eighth"},
		{num: -98, exp: "negative ninety-eighth"},
		{num: 99, exp: "ninety-ninth"},
		{num: -99, exp: "negative ninety-ninth"},
		{num: 100, exp: "one hundredth"},
		{num: -100, exp: "negative one hundredth"},
		{num: 111, exp: "one hundred eleventh"},
		{num: -111, exp: "negative one hundred eleventh"},
		{num: 54_321, exp: "fifty-four thousand three hundred twenty-first"},
		{num: -54_321, exp: "negative fifty-four thousand three hundred twenty-first"},
		{num: 1_234, exp: "one thousand two hundred thirty-fourth"},
		{num: -1_234, exp: "negative one thousand two hundred thirty-fourth"},
		{num: 1_000, exp: "one thousandth"},
		{num: -1_000, exp: "negative one thousandth"},
		{num: 1_001, exp: "one thousand first"},
		{num: -1_001, exp: "negative one thousand first"},
		{num: 1_020, exp: "one thousand twentieth"},
		{num: -1_020, exp: "negative one thousand twentieth"},
		{num: 1_300, exp: "one thousand three hundredth"},
		{num: -1_300, exp: "negative one thousand three hundredth"},
		{num: 1_045, exp: "one thousand forty-fifth"},
		{num: -1_045, exp: "negative one thousand forty-fifth"},
		{num: 1_670, exp: "one thousand six hundred seventieth"},
		{num: -1_670, exp: "negative one thousand six hundred seventieth"},
		{num: 1_809, exp: "one thousand eight hundred ninth"},
		{num: -1_809, exp: "negative one thousand eight hundred ninth"},
		{num: 2_000, exp: "two thousandth"},
		{num: -2_000, exp: "negative two thousandth"},
		{num: 2_001, exp: "two thousand first"},
		{num: -2_001, exp: "negative two thousand first"},
		{num: 2_020, exp: "two thousand twentieth"},
		{num: -2_020, exp: "negative two thousand twentieth"},
		{num: 2_300, exp: "two thousand three hundredth"},
		{num: -2_300, exp: "negative two thousand three hundredth"},
		{num: 2_045, exp: "two thousand forty-fifth"},
		{num: -2_045, exp: "negative two thousand forty-fifth"},
		{num: 2_670, exp: "two thousand six hundred seventieth"},
		{num: -2_670, exp: "negative two thousand six hundred seventieth"},
		{num: 2_809, exp: "two thousand eight hundred ninth"},
		{num: -2_809, exp: "negative two thousand eight hundred ninth"},
		{num: 3_000, exp: "three thousandth"},
		{num: -3_000, exp: "negative three thousandth"},
		{num: 3_001, exp: "three thousand first"},
		{num: -3_001, exp: "negative three thousand first"},
		{num: 3_020, exp: "three thousand twentieth"},
		{num: -3_020, exp: "negative three thousand twentieth"},
		{num: 3_300, exp: "three thousand three hundredth"},
		{num: -3_300, exp: "negative three thousand three hundredth"},
		{num: 3_045, exp: "three thousand forty-fifth"},
		{num: -3_045, exp: "negative three thousand forty-fifth"},
		{num: 3_670, exp: "three thousand six hundred seventieth"},
		{num: -3_670, exp: "negative three thousand six hundred seventieth"},
		{num: 3_809, exp: "three thousand eight hundred ninth"},
		{num: -3_809, exp: "negative three thousand eight hundred ninth"},
		{num: 4_000, exp: "four thousandth"},
		{num: -4_000, exp: "negative four thousandth"},
		{num: 4_001, exp: "four thousand first"},
		{num: -4_001, exp: "negative four thousand first"},
		{num: 4_020, exp: "four thousand twentieth"},
		{num: -4_020, exp: "negative four thousand twentieth"},
		{num: 4_300, exp: "four thousand three hundredth"},
		{num: -4_300, exp: "negative four thousand three hundredth"},
		{num: 4_045, exp: "four thousand forty-fifth"},
		{num: -4_045, exp: "negative four thousand forty-fifth"},
		{num: 4_670, exp: "four thousand six hundred seventieth"},
		{num: -4_670, exp: "negative four thousand six hundred seventieth"},
		{num: 4_809, exp: "four thousand eight hundred ninth"},
		{num: -4_809, exp: "negative four thousand eight hundred ninth"},
		{num: 5_000, exp: "five thousandth"},
		{num: -5_000, exp: "negative five thousandth"},
		{num: 5_001, exp: "five thousand first"},
		{num: -5_001, exp: "negative five thousand first"},
		{num: 5_020, exp: "five thousand twentieth"},
		{num: -5_020, exp: "negative five thousand twentieth"},
		{num: 5_300, exp: "five thousand three hundredth"},
		{num: -5_300, exp: "negative five thousand three hundredth"},
		{num: 5_045, exp: "five thousand forty-fifth"},
		{num: -5_045, exp: "negative five thousand forty-fifth"},
		{num: 5_670, exp: "five thousand six hundred seventieth"},
		{num: -5_670, exp: "negative five thousand six hundred seventieth"},
		{num: 5_809, exp: "five thousand eight hundred ninth"},
		{num: -5_809, exp: "negative five thousand eight hundred ninth"},
		{num: 6_000, exp: "six thousandth"},
		{num: -6_000, exp: "negative six thousandth"},
		{num: 6_001, exp: "six thousand first"},
		{num: -6_001, exp: "negative six thousand first"},
		{num: 6_020, exp: "six thousand twentieth"},
		{num: -6_020, exp: "negative six thousand twentieth"},
		{num: 6_300, exp: "six thousand three hundredth"},
		{num: -6_300, exp: "negative six thousand three hundredth"},
		{num: 6_045, exp: "six thousand forty-fifth"},
		{num: -6_045, exp: "negative six thousand forty-fifth"},
		{num: 6_670, exp: "six thousand six hundred seventieth"},
		{num: -6_670, exp: "negative six thousand six hundred seventieth"},
		{num: 6_809, exp: "six thousand eight hundred ninth"},
		{num: -6_809, exp: "negative six thousand eight hundred ninth"},
		{num: 7_000, exp: "seven thousandth"},
		{num: -7_000, exp: "negative seven thousandth"},
		{num: 7_001, exp: "seven thousand first"},
		{num: -7_001, exp: "negative seven thousand first"},
		{num: 7_020, exp: "seven thousand twentieth"},
		{num: -7_020, exp: "negative seven thousand twentieth"},
		{num: 7_300, exp: "seven thousand three hundredth"},
		{num: -7_300, exp: "negative seven thousand three hundredth"},
		{num: 7_045, exp: "seven thousand forty-fifth"},
		{num: -7_045, exp: "negative seven thousand forty-fifth"},
		{num: 7_670, exp: "seven thousand six hundred seventieth"},
		{num: -7_670, exp: "negative seven thousand six hundred seventieth"},
		{num: 7_809, exp: "seven thousand eight hundred ninth"},
		{num: -7_809, exp: "negative seven thousand eight hundred ninth"},
		{num: 8_000, exp: "eight thousandth"},
		{num: -8_000, exp: "negative eight thousandth"},
		{num: 8_001, exp: "eight thousand first"},
		{num: -8_001, exp: "negative eight thousand first"},
		{num: 8_020, exp: "eight thousand twentieth"},
		{num: -8_020, exp: "negative eight thousand twentieth"},
		{num: 8_300, exp: "eight thousand three hundredth"},
		{num: -8_300, exp: "negative eight thousand three hundredth"},
		{num: 8_045, exp: "eight thousand forty-fifth"},
		{num: -8_045, exp: "negative eight thousand forty-fifth"},
		{num: 8_670, exp: "eight thousand six hundred seventieth"},
		{num: -8_670, exp: "negative eight thousand six hundred seventieth"},
		{num: 8_809, exp: "eight thousand eight hundred ninth"},
		{num: -8_809, exp: "negative eight thousand eight hundred ninth"},
		{num: 9_000, exp: "nine thousandth"},
		{num: -9_000, exp: "negative nine thousandth"},
		{num: 9_001, exp: "nine thousand first"},
		{num: -9_001, exp: "negative nine thousand first"},
		{num: 9_020, exp: "nine thousand twentieth"},
		{num: -9_020, exp: "negative nine thousand twentieth"},
		{num: 9_300, exp: "nine thousand three hundredth"},
		{num: -9_300, exp: "negative nine thousand three hundredth"},
		{num: 9_045, exp: "nine thousand forty-fifth"},
		{num: -9_045, exp: "negative nine thousand forty-fifth"},
		{num: 9_670, exp: "nine thousand six hundred seventieth"},
		{num: -9_670, exp: "negative nine thousand six hundred seventieth"},
		{num: 9_809, exp: "nine thousand eight hundred ninth"},
		{num: -9_809, exp: "negative nine thousand eight hundred ninth"},
		{num: 9_999, exp: "nine thousand nine hundred ninety-ninth"},
		{num: -9_999, exp: "negative nine thousand nine hundred ninety-ninth"},
		{num: 10_000, exp: "ten thousandth"},
		{num: -10_000, exp: "negative ten thousandth"},
		{num: 24_745, exp: "twenty-four thousand seven hundred forty-fifth"},
		{num: -24_745, exp: "negative twenty-four thousand seven hundred forty-fifth"},
		{num: 99_999, exp: "ninety-nine thousand nine hundred ninety-ninth"},
		{num: -99_999, exp: "negative ninety-nine thousand nine hundred ninety-ninth"},
		{num: 100_000, exp: "one hundred thousandth"},
		{num: -100_000, exp: "negative one hundred thousandth"},
		{num: 552_887, exp: "five hundred fifty-two thousand eight hundred eighty-seventh"},
		{num: -552_887, exp: "negative five hundred fifty-two thousand eight hundred eighty-seventh"},
		{num: 1_000_000, exp: "one millionth"},
		{num: -1_000_000, exp: "negative one millionth"},
		{num: 1_002_003, exp: "one million two thousand third"},
		{num: -1_002_003, exp: "negative one million two thousand third"},
		{num: 5_485_065, exp: "five million four hundred eighty-five thousand sixty-fifth"},
		{num: -5_485_065, exp: "negative five million four hundred eighty-five thousand sixty-fifth"},
		{num: 10_000_000, exp: "ten millionth"},
		{num: -10_000_000, exp: "negative ten millionth"},
		{num: 82_212_496, exp: "eighty-two million two hundred twelve thousand four hundred ninety-sixth"},
		{num: -82_212_496, exp: "negative eighty-two million two hundred twelve thousand four hundred ninety-sixth"},
		{num: 100_000_000, exp: "one hundred millionth"},
		{num: -100_000_000, exp: "negative one hundred millionth"},
		{num: 100_200_300, exp: "one hundred million two hundred thousand three hundredth"},
		{num: -100_200_300, exp: "negative one hundred million two hundred thousand three hundredth"},
		{num: 126_490_799,
			exp: "one hundred twenty-six million four hundred ninety thousand seven hundred ninety-ninth"},
		{num: -126_490_799,
			exp: "negative one hundred twenty-six million four hundred ninety thousand seven hundred ninety-ninth"},
		{num: 1_000_000_000, exp: "one billionth"},
		{num: -1_000_000_000, exp: "negative one billionth"},
		{num: 9_007_912_442,
			exp: "nine billion seven million nine hundred twelve thousand four hundred forty-second"},
		{num: -9_007_912_442,
			exp: "negative nine billion seven million nine hundred twelve thousand four hundred forty-second"},
		{num: 10_000_000_000, exp: "ten billionth"},
		{num: -10_000_000_000, exp: "negative ten billionth"},
		{num: 10_000_000_030, exp: "ten billion thirtieth"},
		{num: -10_000_000_030, exp: "negative ten billion thirtieth"},
		{num: 10_000_030_000, exp: "ten billion thirty thousandth"},
		{num: -10_000_030_000, exp: "negative ten billion thirty thousandth"},
		{num: 64_127_772_414,
			exp: "sixty-four billion one hundred twenty-seven million " +
				"seven hundred seventy-two thousand four hundred fourteenth"},
		{num: -64_127_772_414,
			exp: "negative sixty-four billion one hundred twenty-seven million " +
				"seven hundred seventy-two thousand four hundred fourteenth"},
		{num: 100_000_000_000, exp: "one hundred billionth"},
		{num: -100_000_000_000, exp: "negative one hundred billionth"},
		{num: 759_528_730_112,
			exp: "seven hundred fifty-nine billion five hundred twenty-eight million " +
				"seven hundred thirty thousand one hundred twelfth"},
		{num: -759_528_730_112,
			exp: "negative seven hundred fifty-nine billion five hundred twenty-eight million " +
				"seven hundred thirty thousand one hundred twelfth"},
		{num: 1_000_000_000_000, exp: "one trillionth"},
		{num: -1_000_000_000_000, exp: "negative one trillionth"},
		{num: 9_515_965_217_456,
			exp: "nine trillion five hundred fifteen billion " +
				"nine hundred sixty-five million two hundred seventeen thousand four hundred fifty-sixth"},
		{num: -9_515_965_217_456,
			exp: "negative nine trillion five hundred fifteen billion " +
				"nine hundred sixty-five million two hundred seventeen thousand four hundred fifty-sixth"},
		{num: 10_000_000_000_000, exp: "ten trillionth"},
		{num: -10_000_000_000_000, exp: "negative ten trillionth"},
		{num: 50_558_442_088_500,
			exp: "fifty trillion five hundred fifty-eight billion " +
				"four hundred forty-two million eighty-eight thousand five hundredth"},
		{num: -50_558_442_088_500,
			exp: "negative fifty trillion five hundred fifty-eight billion " +
				"four hundred forty-two million eighty-eight thousand five hundredth"},
		{num: 100_000_000_000_000, exp: "one hundred trillionth"},
		{num: -100_000_000_000_000, exp: "negative one hundred trillionth"},
		{num: 875_545_170_963_847,
			exp: "eight hundred seventy-five trillion five hundred forty-five billion " +
				"one hundred seventy million nine hundred sixty-three thousand eight hundred forty-seventh"},
		{num: -875_545_170_963_847,
			exp: "negative eight hundred seventy-five trillion five hundred forty-five billion " +
				"one hundred seventy million nine hundred sixty-three thousand eight hundred forty-seventh"},
		{num: 1_000_000_000_000_000, exp: "one quadrillionth"},
		{num: -1_000_000_000_000_000, exp: "negative one quadrillionth"},
		{num: 1_459_010_276_579_858,
			exp: "one quadrillion four hundred fifty-nine trillion " +
				"ten billion two hundred seventy-six million " +
				"five hundred seventy-nine thousand eight hundred fifty-eighth"},
		{num: -1_459_010_276_579_858,
			exp: "negative one quadrillion four hundred fifty-nine trillion " +
				"ten billion two hundred seventy-six million " +
				"five hundred seventy-nine thousand eight hundred fifty-eighth"},
		{num: 10_000_000_000_000_000, exp: "ten quadrillionth"},
		{num: -10_000_000_000_000_000, exp: "negative ten quadrillionth"},
		{num: 63_817_328_483_963_713,
			exp: "sixty-three quadrillion eight hundred seventeen trillion " +
				"three hundred twenty-eight billion four hundred eighty-three million " +
				"nine hundred sixty-three thousand seven hundred thirteenth"},
		{num: -63_817_328_483_963_713,
			exp: "negative sixty-three quadrillion eight hundred seventeen trillion " +
				"three hundred twenty-eight billion four hundred eighty-three million " +
				"nine hundred sixty-three thousand seven hundred thirteenth"},
		{num: 100_000_000_000_000_000, exp: "one hundred quadrillionth"},
		{num: -100_000_000_000_000_000, exp: "negative one hundred quadrillionth"},
		{num: 503_030_044_673_410_914,
			exp: "five hundred three quadrillion thirty trillion " +
				"forty-four billion six hundred seventy-three million " +
				"four hundred ten thousand nine hundred fourteenth"},
		{num: -503_030_044_673_410_914,
			exp: "negative five hundred three quadrillion thirty trillion " +
				"forty-four billion six hundred seventy-three million " +
				"four hundred ten thousand nine hundred fourteenth"},
		{num: 1_000_000_000_000_000_000, exp: "one quintillionth"},
		{num: -1_000_000_000_000_000_000, exp: "negative one quintillionth"},
		{num: 1_002_003_004_005_006_007,
			exp: "one quintillion two quadrillion three trillion " +
				"four billion five million six thousand seventh"},
		{num: -1_002_003_004_005_006_007,
			exp: "negative one quintillion two quadrillion three trillion " +
				"four billion five million six thousand seventh"},
		{num: 6_095_934_577_086_450_739,
			exp: "six quintillion ninety-five quadrillion nine hundred thirty-four trillion " +
				"five hundred seventy-seven billion eighty-six million " +
				"four hundred fifty thousand seven hundred thirty-ninth"},
		{num: -6_095_934_577_086_450_739,
			exp: "negative six quintillion ninety-five quadrillion nine hundred thirty-four trillion " +
				"five hundred seventy-seven billion eighty-six million " +
				"four hundred fifty thousand seven hundred thirty-ninth"},
		{num: 126, exp: "one hundred twenty-sixth"},
		{num: 127, exp: "one hundred twenty-seventh"},
		{num: 128, exp: "one hundred twenty-eighth"},
		{num: -127, exp: "negative one hundred twenty-seventh"},
		{num: -128, exp: "negative one hundred twenty-eighth"},
		{num: -129, exp: "negative one hundred twenty-ninth"},
		{num: 254, exp: "two hundred fifty-fourth"},
		{num: 255, exp: "two hundred fifty-fifth"},
		{num: 256, exp: "two hundred fifty-sixth"},
		{num: 32_766, exp: "thirty-two thousand seven hundred sixty-sixth"},
		{num: 32_767, exp: "thirty-two thousand seven hundred sixty-seventh"},
		{num: 32_768, exp: "thirty-two thousand seven hundred sixty-eighth"},
		{num: -32_767, exp: "negative thirty-two thousand seven hundred sixty-seventh"},
		{num: -32_768, exp: "negative thirty-two thousand seven hundred sixty-eighth"},
		{num: -32_769, exp: "negative thirty-two thousand seven hundred sixty-ninth"},
		{num: 65_534, exp: "sixty-five thousand five hundred thirty-fourth"},
		{num: 65_535, exp: "sixty-five thousand five hundred thirty-fifth"},
		{num: 65_536, exp: "sixty-five thousand five hundred thirty-sixth"},
		{num: 2_147_483_646,
			exp: "two billion one hundred forty-seven million " +
				"four hundred eighty-three thousand six hundred forty-sixth"},
		{num: 2_147_483_647,
			exp: "two billion one hundred forty-seven million " +
				"four hundred eighty-three thousand six hundred forty-seventh"},
		{num: 2_147_483_648,
			exp: "two billion one hundred forty-seven million " +
				"four hundred eighty-three thousand six hundred forty-eighth"},
		{num: -2_147_483_647,
			exp: "negative two billion one hundred forty-seven million " +
				"four hundred eighty-three thousand six hundred forty-seventh"},
		{num: -2_147_483_648,
			exp: "negative two billion one hundred forty-seven million " +
				"four hundred eighty-three thousand six hundred forty-eighth"},
		{num: -2_147_483_649,
			exp: "negative two billion one hundred forty-seven million " +
				"four hundred eighty-three thousand six hundred forty-ninth"},
		{num: 4_294_967_294,
			exp: "four billion two hundred ninety-four million " +
				"nine hundred sixty-seven thousand two hundred ninety-fourth"},
		{num: 4_294_967_295,
			exp: "four billion two hundred ninety-four million " +
				"nine hundred sixty-seven thousand two hundred ninety-fifth"},
		{num: 4_294_967_296,
			exp: "four billion two hundred ninety-four million " +
				"nine hundred sixty-seven thousand two hundred ninety-sixth"},
		{num: 9_223_372_036_854_775_806,
			exp: "nine quintillion two hundred twenty-three quadrillion " +
				"three hundred seventy-two trillion thirty-six billion " +
				"eight hundred fifty-four million seven hundred seventy-five thousand eight hundred sixth"},
		{num: 9_223_372_036_854_775_807,
			exp: "nine quintillion two hundred twenty-three quadrillion " +
				"three hundred seventy-two trillion thirty-six billion " +
				"eight hundred fifty-four million seven hundred seventy-five thousand eight hundred seventh"},
		{num: -9_223_372_036_854_775_807,
			exp: "negative nine quintillion two hundred twenty-three quadrillion " +
				"three hundred seventy-two trillion thirty-six billion " +
				"eight hundred fifty-four million seven hundred seventy-five thousand eight hundred seventh"},
		{num: -9_223_372_036_854_775_808,
			exp: "negative nine quintillion two hundred twenty-three quadrillion " +
				"three hundred seventy-two trillion thirty-six billion " +
				"eight hundred fifty-four million seven hundred seventy-five thousand eight hundred eighth"},
	}

	for _, tc := range tests {
		t.Run(fmt.Sprintf("%d", tc.num), func(t *testing.T) {
			var act string
			testFunc := func() {
				act = IthWords(tc.num)
			}
			require.NotPanics(t, testFunc, "IthWords(%d)", tc.num)
			assert.Equal(t, tc.exp, act, "IthWords(%d)", tc.num)
		})
	}
}

func TestWordsToIth(t *testing.T) {
	// Assuming IthWords uses WordsToIth, so only doing edge-case tests in here.
	tests := []struct {
		name string
		val  string
		exp  string
	}{
		{
			name: "empty string",
			val:  "",
			exp:  "",
		},
		{
			name: "ends with something else",
			val:  "this is something else",
			exp:  "this is something elseth",
		},
		{
			name: "raw number",
			val:  "123",
			exp:  "123th",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			var act string
			testFunc := func() {
				act = WordsToIth(tc.val)
			}
			require.NotPanics(t, testFunc, "WordsToIth(%q)", tc.val)
			assert.Equal(t, tc.exp, act, "WordsToIth(%q) result", tc.val)
		})
	}
}
