package to_words

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIntToDigits(t *testing.T) {
	tests := []struct {
		num int
		exp string
	}{
		{num: 0, exp: "zero"},
		{num: 1, exp: "one"},
		{num: -1, exp: "negative one"},
		{num: 2, exp: "two"},
		{num: -2, exp: "negative two"},
		{num: 3, exp: "three"},
		{num: -3, exp: "negative three"},
		{num: 4, exp: "four"},
		{num: -4, exp: "negative four"},
		{num: 5, exp: "five"},
		{num: -5, exp: "negative five"},
		{num: 6, exp: "six"},
		{num: -6, exp: "negative six"},
		{num: 7, exp: "seven"},
		{num: -7, exp: "negative seven"},
		{num: 8, exp: "eight"},
		{num: -8, exp: "negative eight"},
		{num: 9, exp: "nine"},
		{num: -9, exp: "negative nine"},
		{num: 10, exp: "one zero"},
		{num: -10, exp: "negative one zero"},
		{num: 11, exp: "one one"},
		{num: -11, exp: "negative one one"},
		{num: 12, exp: "one two"},
		{num: -12, exp: "negative one two"},
		{num: 13, exp: "one three"},
		{num: -13, exp: "negative one three"},
		{num: 14, exp: "one four"},
		{num: -14, exp: "negative one four"},
		{num: 15, exp: "one five"},
		{num: -15, exp: "negative one five"},
		{num: 16, exp: "one six"},
		{num: -16, exp: "negative one six"},
		{num: 17, exp: "one seven"},
		{num: -17, exp: "negative one seven"},
		{num: 18, exp: "one eight"},
		{num: -18, exp: "negative one eight"},
		{num: 19, exp: "one nine"},
		{num: -19, exp: "negative one nine"},
		{num: 20, exp: "two zero"},
		{num: -20, exp: "negative two zero"},
		{num: 21, exp: "two one"},
		{num: -21, exp: "negative two one"},
		{num: 22, exp: "two two"},
		{num: -22, exp: "negative two two"},
		{num: 23, exp: "two three"},
		{num: -23, exp: "negative two three"},
		{num: 24, exp: "two four"},
		{num: -24, exp: "negative two four"},
		{num: 25, exp: "two five"},
		{num: -25, exp: "negative two five"},
		{num: 26, exp: "two six"},
		{num: -26, exp: "negative two six"},
		{num: 27, exp: "two seven"},
		{num: -27, exp: "negative two seven"},
		{num: 28, exp: "two eight"},
		{num: -28, exp: "negative two eight"},
		{num: 29, exp: "two nine"},
		{num: -29, exp: "negative two nine"},
		{num: 30, exp: "three zero"},
		{num: -30, exp: "negative three zero"},
		{num: 31, exp: "three one"},
		{num: -31, exp: "negative three one"},
		{num: 32, exp: "three two"},
		{num: -32, exp: "negative three two"},
		{num: 33, exp: "three three"},
		{num: -33, exp: "negative three three"},
		{num: 34, exp: "three four"},
		{num: -34, exp: "negative three four"},
		{num: 35, exp: "three five"},
		{num: -35, exp: "negative three five"},
		{num: 36, exp: "three six"},
		{num: -36, exp: "negative three six"},
		{num: 37, exp: "three seven"},
		{num: -37, exp: "negative three seven"},
		{num: 38, exp: "three eight"},
		{num: -38, exp: "negative three eight"},
		{num: 39, exp: "three nine"},
		{num: -39, exp: "negative three nine"},
		{num: 40, exp: "four zero"},
		{num: -40, exp: "negative four zero"},
		{num: 41, exp: "four one"},
		{num: -41, exp: "negative four one"},
		{num: 42, exp: "four two"},
		{num: -42, exp: "negative four two"},
		{num: 43, exp: "four three"},
		{num: -43, exp: "negative four three"},
		{num: 44, exp: "four four"},
		{num: -44, exp: "negative four four"},
		{num: 45, exp: "four five"},
		{num: -45, exp: "negative four five"},
		{num: 46, exp: "four six"},
		{num: -46, exp: "negative four six"},
		{num: 47, exp: "four seven"},
		{num: -47, exp: "negative four seven"},
		{num: 48, exp: "four eight"},
		{num: -48, exp: "negative four eight"},
		{num: 49, exp: "four nine"},
		{num: -49, exp: "negative four nine"},
		{num: 50, exp: "five zero"},
		{num: -50, exp: "negative five zero"},
		{num: 51, exp: "five one"},
		{num: -51, exp: "negative five one"},
		{num: 52, exp: "five two"},
		{num: -52, exp: "negative five two"},
		{num: 53, exp: "five three"},
		{num: -53, exp: "negative five three"},
		{num: 54, exp: "five four"},
		{num: -54, exp: "negative five four"},
		{num: 55, exp: "five five"},
		{num: -55, exp: "negative five five"},
		{num: 56, exp: "five six"},
		{num: -56, exp: "negative five six"},
		{num: 57, exp: "five seven"},
		{num: -57, exp: "negative five seven"},
		{num: 58, exp: "five eight"},
		{num: -58, exp: "negative five eight"},
		{num: 59, exp: "five nine"},
		{num: -59, exp: "negative five nine"},
		{num: 60, exp: "six zero"},
		{num: -60, exp: "negative six zero"},
		{num: 61, exp: "six one"},
		{num: -61, exp: "negative six one"},
		{num: 62, exp: "six two"},
		{num: -62, exp: "negative six two"},
		{num: 63, exp: "six three"},
		{num: -63, exp: "negative six three"},
		{num: 64, exp: "six four"},
		{num: -64, exp: "negative six four"},
		{num: 65, exp: "six five"},
		{num: -65, exp: "negative six five"},
		{num: 66, exp: "six six"},
		{num: -66, exp: "negative six six"},
		{num: 67, exp: "six seven"},
		{num: -67, exp: "negative six seven"},
		{num: 68, exp: "six eight"},
		{num: -68, exp: "negative six eight"},
		{num: 69, exp: "six nine"},
		{num: -69, exp: "negative six nine"},
		{num: 70, exp: "seven zero"},
		{num: -70, exp: "negative seven zero"},
		{num: 71, exp: "seven one"},
		{num: -71, exp: "negative seven one"},
		{num: 72, exp: "seven two"},
		{num: -72, exp: "negative seven two"},
		{num: 73, exp: "seven three"},
		{num: -73, exp: "negative seven three"},
		{num: 74, exp: "seven four"},
		{num: -74, exp: "negative seven four"},
		{num: 75, exp: "seven five"},
		{num: -75, exp: "negative seven five"},
		{num: 76, exp: "seven six"},
		{num: -76, exp: "negative seven six"},
		{num: 77, exp: "seven seven"},
		{num: -77, exp: "negative seven seven"},
		{num: 78, exp: "seven eight"},
		{num: -78, exp: "negative seven eight"},
		{num: 79, exp: "seven nine"},
		{num: -79, exp: "negative seven nine"},
		{num: 80, exp: "eight zero"},
		{num: -80, exp: "negative eight zero"},
		{num: 81, exp: "eight one"},
		{num: -81, exp: "negative eight one"},
		{num: 82, exp: "eight two"},
		{num: -82, exp: "negative eight two"},
		{num: 83, exp: "eight three"},
		{num: -83, exp: "negative eight three"},
		{num: 84, exp: "eight four"},
		{num: -84, exp: "negative eight four"},
		{num: 85, exp: "eight five"},
		{num: -85, exp: "negative eight five"},
		{num: 86, exp: "eight six"},
		{num: -86, exp: "negative eight six"},
		{num: 87, exp: "eight seven"},
		{num: -87, exp: "negative eight seven"},
		{num: 88, exp: "eight eight"},
		{num: -88, exp: "negative eight eight"},
		{num: 89, exp: "eight nine"},
		{num: -89, exp: "negative eight nine"},
		{num: 90, exp: "nine zero"},
		{num: -90, exp: "negative nine zero"},
		{num: 91, exp: "nine one"},
		{num: -91, exp: "negative nine one"},
		{num: 92, exp: "nine two"},
		{num: -92, exp: "negative nine two"},
		{num: 93, exp: "nine three"},
		{num: -93, exp: "negative nine three"},
		{num: 94, exp: "nine four"},
		{num: -94, exp: "negative nine four"},
		{num: 95, exp: "nine five"},
		{num: -95, exp: "negative nine five"},
		{num: 96, exp: "nine six"},
		{num: -96, exp: "negative nine six"},
		{num: 97, exp: "nine seven"},
		{num: -97, exp: "negative nine seven"},
		{num: 98, exp: "nine eight"},
		{num: -98, exp: "negative nine eight"},
		{num: 99, exp: "nine nine"},
		{num: -99, exp: "negative nine nine"},
		{num: 100, exp: "one zero zero"},
		{num: -100, exp: "negative one zero zero"},
		{num: 111, exp: "one one one"},
		{num: -111, exp: "negative one one one"},
		{num: 54_321, exp: "five four three two one"},
		{num: -54_321, exp: "negative five four three two one"},
		{num: 1_234, exp: "one two three four"},
		{num: -1_234, exp: "negative one two three four"},
		{num: 1_000, exp: "one zero zero zero"},
		{num: -1_000, exp: "negative one zero zero zero"},
		{num: 1_001, exp: "one zero zero one"},
		{num: -1_001, exp: "negative one zero zero one"},
		{num: 1_020, exp: "one zero two zero"},
		{num: -1_020, exp: "negative one zero two zero"},
		{num: 1_300, exp: "one three zero zero"},
		{num: -1_300, exp: "negative one three zero zero"},
		{num: 1_045, exp: "one zero four five"},
		{num: -1_045, exp: "negative one zero four five"},
		{num: 1_670, exp: "one six seven zero"},
		{num: -1_670, exp: "negative one six seven zero"},
		{num: 1_809, exp: "one eight zero nine"},
		{num: -1_809, exp: "negative one eight zero nine"},
		{num: 2_000, exp: "two zero zero zero"},
		{num: -2_000, exp: "negative two zero zero zero"},
		{num: 2_001, exp: "two zero zero one"},
		{num: -2_001, exp: "negative two zero zero one"},
		{num: 2_020, exp: "two zero two zero"},
		{num: -2_020, exp: "negative two zero two zero"},
		{num: 2_300, exp: "two three zero zero"},
		{num: -2_300, exp: "negative two three zero zero"},
		{num: 2_045, exp: "two zero four five"},
		{num: -2_045, exp: "negative two zero four five"},
		{num: 2_670, exp: "two six seven zero"},
		{num: -2_670, exp: "negative two six seven zero"},
		{num: 2_809, exp: "two eight zero nine"},
		{num: -2_809, exp: "negative two eight zero nine"},
		{num: 3_000, exp: "three zero zero zero"},
		{num: -3_000, exp: "negative three zero zero zero"},
		{num: 3_001, exp: "three zero zero one"},
		{num: -3_001, exp: "negative three zero zero one"},
		{num: 3_020, exp: "three zero two zero"},
		{num: -3_020, exp: "negative three zero two zero"},
		{num: 3_300, exp: "three three zero zero"},
		{num: -3_300, exp: "negative three three zero zero"},
		{num: 3_045, exp: "three zero four five"},
		{num: -3_045, exp: "negative three zero four five"},
		{num: 3_670, exp: "three six seven zero"},
		{num: -3_670, exp: "negative three six seven zero"},
		{num: 3_809, exp: "three eight zero nine"},
		{num: -3_809, exp: "negative three eight zero nine"},
		{num: 4_000, exp: "four zero zero zero"},
		{num: -4_000, exp: "negative four zero zero zero"},
		{num: 4_001, exp: "four zero zero one"},
		{num: -4_001, exp: "negative four zero zero one"},
		{num: 4_020, exp: "four zero two zero"},
		{num: -4_020, exp: "negative four zero two zero"},
		{num: 4_300, exp: "four three zero zero"},
		{num: -4_300, exp: "negative four three zero zero"},
		{num: 4_045, exp: "four zero four five"},
		{num: -4_045, exp: "negative four zero four five"},
		{num: 4_670, exp: "four six seven zero"},
		{num: -4_670, exp: "negative four six seven zero"},
		{num: 4_809, exp: "four eight zero nine"},
		{num: -4_809, exp: "negative four eight zero nine"},
		{num: 5_000, exp: "five zero zero zero"},
		{num: -5_000, exp: "negative five zero zero zero"},
		{num: 5_001, exp: "five zero zero one"},
		{num: -5_001, exp: "negative five zero zero one"},
		{num: 5_020, exp: "five zero two zero"},
		{num: -5_020, exp: "negative five zero two zero"},
		{num: 5_300, exp: "five three zero zero"},
		{num: -5_300, exp: "negative five three zero zero"},
		{num: 5_045, exp: "five zero four five"},
		{num: -5_045, exp: "negative five zero four five"},
		{num: 5_670, exp: "five six seven zero"},
		{num: -5_670, exp: "negative five six seven zero"},
		{num: 5_809, exp: "five eight zero nine"},
		{num: -5_809, exp: "negative five eight zero nine"},
		{num: 6_000, exp: "six zero zero zero"},
		{num: -6_000, exp: "negative six zero zero zero"},
		{num: 6_001, exp: "six zero zero one"},
		{num: -6_001, exp: "negative six zero zero one"},
		{num: 6_020, exp: "six zero two zero"},
		{num: -6_020, exp: "negative six zero two zero"},
		{num: 6_300, exp: "six three zero zero"},
		{num: -6_300, exp: "negative six three zero zero"},
		{num: 6_045, exp: "six zero four five"},
		{num: -6_045, exp: "negative six zero four five"},
		{num: 6_670, exp: "six six seven zero"},
		{num: -6_670, exp: "negative six six seven zero"},
		{num: 6_809, exp: "six eight zero nine"},
		{num: -6_809, exp: "negative six eight zero nine"},
		{num: 7_000, exp: "seven zero zero zero"},
		{num: -7_000, exp: "negative seven zero zero zero"},
		{num: 7_001, exp: "seven zero zero one"},
		{num: -7_001, exp: "negative seven zero zero one"},
		{num: 7_020, exp: "seven zero two zero"},
		{num: -7_020, exp: "negative seven zero two zero"},
		{num: 7_300, exp: "seven three zero zero"},
		{num: -7_300, exp: "negative seven three zero zero"},
		{num: 7_045, exp: "seven zero four five"},
		{num: -7_045, exp: "negative seven zero four five"},
		{num: 7_670, exp: "seven six seven zero"},
		{num: -7_670, exp: "negative seven six seven zero"},
		{num: 7_809, exp: "seven eight zero nine"},
		{num: -7_809, exp: "negative seven eight zero nine"},
		{num: 8_000, exp: "eight zero zero zero"},
		{num: -8_000, exp: "negative eight zero zero zero"},
		{num: 8_001, exp: "eight zero zero one"},
		{num: -8_001, exp: "negative eight zero zero one"},
		{num: 8_020, exp: "eight zero two zero"},
		{num: -8_020, exp: "negative eight zero two zero"},
		{num: 8_300, exp: "eight three zero zero"},
		{num: -8_300, exp: "negative eight three zero zero"},
		{num: 8_045, exp: "eight zero four five"},
		{num: -8_045, exp: "negative eight zero four five"},
		{num: 8_670, exp: "eight six seven zero"},
		{num: -8_670, exp: "negative eight six seven zero"},
		{num: 8_809, exp: "eight eight zero nine"},
		{num: -8_809, exp: "negative eight eight zero nine"},
		{num: 9_000, exp: "nine zero zero zero"},
		{num: -9_000, exp: "negative nine zero zero zero"},
		{num: 9_001, exp: "nine zero zero one"},
		{num: -9_001, exp: "negative nine zero zero one"},
		{num: 9_020, exp: "nine zero two zero"},
		{num: -9_020, exp: "negative nine zero two zero"},
		{num: 9_300, exp: "nine three zero zero"},
		{num: -9_300, exp: "negative nine three zero zero"},
		{num: 9_045, exp: "nine zero four five"},
		{num: -9_045, exp: "negative nine zero four five"},
		{num: 9_670, exp: "nine six seven zero"},
		{num: -9_670, exp: "negative nine six seven zero"},
		{num: 9_809, exp: "nine eight zero nine"},
		{num: -9_809, exp: "negative nine eight zero nine"},
		{num: 9_999, exp: "nine nine nine nine"},
		{num: -9_999, exp: "negative nine nine nine nine"},
		{num: 10_000, exp: "one zero zero zero zero"},
		{num: -10_000, exp: "negative one zero zero zero zero"},
		{num: 24_745, exp: "two four seven four five"},
		{num: -24_745, exp: "negative two four seven four five"},
		{num: 99_999, exp: "nine nine nine nine nine"},
		{num: -99_999, exp: "negative nine nine nine nine nine"},
		{num: 100_000, exp: "one zero zero zero zero zero"},
		{num: -100_000, exp: "negative one zero zero zero zero zero"},
		{num: 552_887, exp: "five five two eight eight seven"},
		{num: -552_887, exp: "negative five five two eight eight seven"},
		{num: 1_000_000, exp: "one zero zero zero zero zero zero"},
		{num: -1_000_000, exp: "negative one zero zero zero zero zero zero"},
		{num: 1_002_003, exp: "one zero zero two zero zero three"},
		{num: -1_002_003, exp: "negative one zero zero two zero zero three"},
		{num: 5_485_065, exp: "five four eight five zero six five"},
		{num: -5_485_065, exp: "negative five four eight five zero six five"},
		{num: 10_000_000, exp: "one zero zero zero zero zero zero zero"},
		{num: -10_000_000, exp: "negative one zero zero zero zero zero zero zero"},
		{num: 82_212_496, exp: "eight two two one two four nine six"},
		{num: -82_212_496, exp: "negative eight two two one two four nine six"},
		{num: 100_000_000, exp: "one zero zero zero zero zero zero zero zero"},
		{num: -100_000_000, exp: "negative one zero zero zero zero zero zero zero zero"},
		{num: 100_200_300, exp: "one zero zero two zero zero three zero zero"},
		{num: -100_200_300, exp: "negative one zero zero two zero zero three zero zero"},
		{num: 126_490_799, exp: "one two six four nine zero seven nine nine"},
		{num: -126_490_799, exp: "negative one two six four nine zero seven nine nine"},
		{num: 1_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero"},
		{num: -1_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero"},
		{num: 9_007_912_442, exp: "nine zero zero seven nine one two four four two"},
		{num: -9_007_912_442, exp: "negative nine zero zero seven nine one two four four two"},
		{num: 10_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero"},
		{num: -10_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero"},
		{num: 10_000_000_030, exp: "one zero zero zero zero zero zero zero zero three zero"},
		{num: -10_000_000_030, exp: "negative one zero zero zero zero zero zero zero zero three zero"},
		{num: 10_000_030_000, exp: "one zero zero zero zero zero three zero zero zero zero"},
		{num: -10_000_030_000, exp: "negative one zero zero zero zero zero three zero zero zero zero"},
		{num: 64_127_772_414, exp: "six four one two seven seven seven two four one four"},
		{num: -64_127_772_414, exp: "negative six four one two seven seven seven two four one four"},
		{num: 100_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero"},
		{num: -100_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 759_528_730_112, exp: "seven five nine five two eight seven three zero one one two"},
		{num: -759_528_730_112, exp: "negative seven five nine five two eight seven three zero one one two"},
		{num: 1_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: -1_000_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 9_515_965_217_456, exp: "nine five one five nine six five two one seven four five six"},
		{num: -9_515_965_217_456, exp: "negative nine five one five nine six five two one seven four five six"},
		{num: 10_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: -10_000_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 50_558_442_088_500, exp: "five zero five five eight four four two zero eight eight five zero zero"},
		{num: -50_558_442_088_500, exp: "negative five zero five five eight four four two zero eight eight five zero zero"},
		{num: 100_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: -100_000_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 875_545_170_963_847, exp: "eight seven five five four five one seven zero nine six three eight four seven"},
		{num: -875_545_170_963_847, exp: "negative eight seven five five four five one seven zero nine six three eight four seven"},
		{num: 1_000_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: -1_000_000_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 1_459_010_276_579_858, exp: "one four five nine zero one zero two seven six five seven nine eight five eight"},
		{num: -1_459_010_276_579_858, exp: "negative one four five nine zero one zero two seven six five seven nine eight five eight"},
		{num: 10_000_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: -10_000_000_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 63_817_328_483_963_713, exp: "six three eight one seven three two eight four eight three nine six three seven one three"},
		{num: -63_817_328_483_963_713, exp: "negative six three eight one seven three two eight four eight three nine six three seven one three"},
		{num: 100_000_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: -100_000_000_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 503_030_044_673_410_914, exp: "five zero three zero three zero zero four four six seven three four one zero nine one four"},
		{num: -503_030_044_673_410_914, exp: "negative five zero three zero three zero zero four four six seven three four one zero nine one four"},
		{num: 1_000_000_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: -1_000_000_000_000_000_000, exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 1_002_003_004_005_006_007, exp: "one zero zero two zero zero three zero zero four zero zero five zero zero six zero zero seven"},
		{num: -1_002_003_004_005_006_007, exp: "negative one zero zero two zero zero three zero zero four zero zero five zero zero six zero zero seven"},
		{num: 6_095_934_577_086_450_739, exp: "six zero nine five nine three four five seven seven zero eight six four five zero seven three nine"},
		{num: -6_095_934_577_086_450_739, exp: "negative six zero nine five nine three four five seven seven zero eight six four five zero seven three nine"},
		{num: 126, exp: "one two six"},
		{num: 127, exp: "one two seven"},
		{num: 128, exp: "one two eight"},
		{num: -127, exp: "negative one two seven"},
		{num: -128, exp: "negative one two eight"},
		{num: -129, exp: "negative one two nine"},
		{num: 254, exp: "two five four"},
		{num: 255, exp: "two five five"},
		{num: 256, exp: "two five six"},
		{num: 32_766, exp: "three two seven six six"},
		{num: 32_767, exp: "three two seven six seven"},
		{num: 32_768, exp: "three two seven six eight"},
		{num: -32_767, exp: "negative three two seven six seven"},
		{num: -32_768, exp: "negative three two seven six eight"},
		{num: -32_769, exp: "negative three two seven six nine"},
		{num: 65_534, exp: "six five five three four"},
		{num: 65_535, exp: "six five five three five"},
		{num: 65_536, exp: "six five five three six"},
		{num: 2_147_483_646, exp: "two one four seven four eight three six four six"},
		{num: 2_147_483_647, exp: "two one four seven four eight three six four seven"},
		{num: 2_147_483_648, exp: "two one four seven four eight three six four eight"},
		{num: -2_147_483_647, exp: "negative two one four seven four eight three six four seven"},
		{num: -2_147_483_648, exp: "negative two one four seven four eight three six four eight"},
		{num: -2_147_483_649, exp: "negative two one four seven four eight three six four nine"},
		{num: 4_294_967_294, exp: "four two nine four nine six seven two nine four"},
		{num: 4_294_967_295, exp: "four two nine four nine six seven two nine five"},
		{num: 4_294_967_296, exp: "four two nine four nine six seven two nine six"},
		{num: 9_223_372_036_854_775_806, exp: "nine two two three three seven two zero three six eight five four seven seven five eight zero six"},
		{num: 9_223_372_036_854_775_807, exp: "nine two two three three seven two zero three six eight five four seven seven five eight zero seven"},
		{num: -9_223_372_036_854_775_807, exp: "negative nine two two three three seven two zero three six eight five four seven seven five eight zero seven"},
		{num: -9_223_372_036_854_775_808, exp: "negative nine two two three three seven two zero three six eight five four seven seven five eight zero eight"},
	}

	for _, tc := range tests {
		t.Run(fmt.Sprintf("%d", tc.num), func(t *testing.T) {
			var act string
			testFunc := func() {
				act = IntToDigits(tc.num)
			}
			require.NotPanics(t, testFunc, "IntToDigits(%d)", tc.num)
			assert.Equal(t, tc.exp, act, "IntToDigits(%d)", tc.num)
		})
	}
}

func TestUintToDigits(t *testing.T) {
	tests := []struct {
		num uint
		exp string
	}{
		{num: 0, exp: "zero"},
		{num: 1, exp: "one"},
		{num: 2, exp: "two"},
		{num: 3, exp: "three"},
		{num: 4, exp: "four"},
		{num: 5, exp: "five"},
		{num: 6, exp: "six"},
		{num: 7, exp: "seven"},
		{num: 8, exp: "eight"},
		{num: 9, exp: "nine"},
		{num: 10, exp: "one zero"},
		{num: 11, exp: "one one"},
		{num: 12, exp: "one two"},
		{num: 13, exp: "one three"},
		{num: 14, exp: "one four"},
		{num: 15, exp: "one five"},
		{num: 16, exp: "one six"},
		{num: 17, exp: "one seven"},
		{num: 18, exp: "one eight"},
		{num: 19, exp: "one nine"},
		{num: 20, exp: "two zero"},
		{num: 21, exp: "two one"},
		{num: 22, exp: "two two"},
		{num: 23, exp: "two three"},
		{num: 24, exp: "two four"},
		{num: 25, exp: "two five"},
		{num: 26, exp: "two six"},
		{num: 27, exp: "two seven"},
		{num: 28, exp: "two eight"},
		{num: 29, exp: "two nine"},
		{num: 30, exp: "three zero"},
		{num: 31, exp: "three one"},
		{num: 32, exp: "three two"},
		{num: 33, exp: "three three"},
		{num: 34, exp: "three four"},
		{num: 35, exp: "three five"},
		{num: 36, exp: "three six"},
		{num: 37, exp: "three seven"},
		{num: 38, exp: "three eight"},
		{num: 39, exp: "three nine"},
		{num: 40, exp: "four zero"},
		{num: 41, exp: "four one"},
		{num: 42, exp: "four two"},
		{num: 43, exp: "four three"},
		{num: 44, exp: "four four"},
		{num: 45, exp: "four five"},
		{num: 46, exp: "four six"},
		{num: 47, exp: "four seven"},
		{num: 48, exp: "four eight"},
		{num: 49, exp: "four nine"},
		{num: 50, exp: "five zero"},
		{num: 51, exp: "five one"},
		{num: 52, exp: "five two"},
		{num: 53, exp: "five three"},
		{num: 54, exp: "five four"},
		{num: 55, exp: "five five"},
		{num: 56, exp: "five six"},
		{num: 57, exp: "five seven"},
		{num: 58, exp: "five eight"},
		{num: 59, exp: "five nine"},
		{num: 60, exp: "six zero"},
		{num: 61, exp: "six one"},
		{num: 62, exp: "six two"},
		{num: 63, exp: "six three"},
		{num: 64, exp: "six four"},
		{num: 65, exp: "six five"},
		{num: 66, exp: "six six"},
		{num: 67, exp: "six seven"},
		{num: 68, exp: "six eight"},
		{num: 69, exp: "six nine"},
		{num: 70, exp: "seven zero"},
		{num: 71, exp: "seven one"},
		{num: 72, exp: "seven two"},
		{num: 73, exp: "seven three"},
		{num: 74, exp: "seven four"},
		{num: 75, exp: "seven five"},
		{num: 76, exp: "seven six"},
		{num: 77, exp: "seven seven"},
		{num: 78, exp: "seven eight"},
		{num: 79, exp: "seven nine"},
		{num: 80, exp: "eight zero"},
		{num: 81, exp: "eight one"},
		{num: 82, exp: "eight two"},
		{num: 83, exp: "eight three"},
		{num: 84, exp: "eight four"},
		{num: 85, exp: "eight five"},
		{num: 86, exp: "eight six"},
		{num: 87, exp: "eight seven"},
		{num: 88, exp: "eight eight"},
		{num: 89, exp: "eight nine"},
		{num: 90, exp: "nine zero"},
		{num: 91, exp: "nine one"},
		{num: 92, exp: "nine two"},
		{num: 93, exp: "nine three"},
		{num: 94, exp: "nine four"},
		{num: 95, exp: "nine five"},
		{num: 96, exp: "nine six"},
		{num: 97, exp: "nine seven"},
		{num: 98, exp: "nine eight"},
		{num: 99, exp: "nine nine"},
		{num: 100, exp: "one zero zero"},
		{num: 111, exp: "one one one"},
		{num: 54_321, exp: "five four three two one"},
		{num: 1_234, exp: "one two three four"},
		{num: 1_000, exp: "one zero zero zero"},
		{num: 1_001, exp: "one zero zero one"},
		{num: 1_020, exp: "one zero two zero"},
		{num: 1_300, exp: "one three zero zero"},
		{num: 1_045, exp: "one zero four five"},
		{num: 1_670, exp: "one six seven zero"},
		{num: 1_809, exp: "one eight zero nine"},
		{num: 2_000, exp: "two zero zero zero"},
		{num: 2_001, exp: "two zero zero one"},
		{num: 2_020, exp: "two zero two zero"},
		{num: 2_300, exp: "two three zero zero"},
		{num: 2_045, exp: "two zero four five"},
		{num: 2_670, exp: "two six seven zero"},
		{num: 2_809, exp: "two eight zero nine"},
		{num: 3_000, exp: "three zero zero zero"},
		{num: 3_001, exp: "three zero zero one"},
		{num: 3_020, exp: "three zero two zero"},
		{num: 3_300, exp: "three three zero zero"},
		{num: 3_045, exp: "three zero four five"},
		{num: 3_670, exp: "three six seven zero"},
		{num: 3_809, exp: "three eight zero nine"},
		{num: 4_000, exp: "four zero zero zero"},
		{num: 4_001, exp: "four zero zero one"},
		{num: 4_020, exp: "four zero two zero"},
		{num: 4_300, exp: "four three zero zero"},
		{num: 4_045, exp: "four zero four five"},
		{num: 4_670, exp: "four six seven zero"},
		{num: 4_809, exp: "four eight zero nine"},
		{num: 5_000, exp: "five zero zero zero"},
		{num: 5_001, exp: "five zero zero one"},
		{num: 5_020, exp: "five zero two zero"},
		{num: 5_300, exp: "five three zero zero"},
		{num: 5_045, exp: "five zero four five"},
		{num: 5_670, exp: "five six seven zero"},
		{num: 5_809, exp: "five eight zero nine"},
		{num: 6_000, exp: "six zero zero zero"},
		{num: 6_001, exp: "six zero zero one"},
		{num: 6_020, exp: "six zero two zero"},
		{num: 6_300, exp: "six three zero zero"},
		{num: 6_045, exp: "six zero four five"},
		{num: 6_670, exp: "six six seven zero"},
		{num: 6_809, exp: "six eight zero nine"},
		{num: 7_000, exp: "seven zero zero zero"},
		{num: 7_001, exp: "seven zero zero one"},
		{num: 7_020, exp: "seven zero two zero"},
		{num: 7_300, exp: "seven three zero zero"},
		{num: 7_045, exp: "seven zero four five"},
		{num: 7_670, exp: "seven six seven zero"},
		{num: 7_809, exp: "seven eight zero nine"},
		{num: 8_000, exp: "eight zero zero zero"},
		{num: 8_001, exp: "eight zero zero one"},
		{num: 8_020, exp: "eight zero two zero"},
		{num: 8_300, exp: "eight three zero zero"},
		{num: 8_045, exp: "eight zero four five"},
		{num: 8_670, exp: "eight six seven zero"},
		{num: 8_809, exp: "eight eight zero nine"},
		{num: 9_000, exp: "nine zero zero zero"},
		{num: 9_001, exp: "nine zero zero one"},
		{num: 9_020, exp: "nine zero two zero"},
		{num: 9_300, exp: "nine three zero zero"},
		{num: 9_045, exp: "nine zero four five"},
		{num: 9_670, exp: "nine six seven zero"},
		{num: 9_809, exp: "nine eight zero nine"},
		{num: 9_999, exp: "nine nine nine nine"},
		{num: 10_000, exp: "one zero zero zero zero"},
		{num: 24_745, exp: "two four seven four five"},
		{num: 99_999, exp: "nine nine nine nine nine"},
		{num: 100_000, exp: "one zero zero zero zero zero"},
		{num: 552_887, exp: "five five two eight eight seven"},
		{num: 1_000_000, exp: "one zero zero zero zero zero zero"},
		{num: 1_002_003, exp: "one zero zero two zero zero three"},
		{num: 5_485_065, exp: "five four eight five zero six five"},
		{num: 10_000_000, exp: "one zero zero zero zero zero zero zero"},
		{num: 82_212_496, exp: "eight two two one two four nine six"},
		{num: 100_000_000, exp: "one zero zero zero zero zero zero zero zero"},
		{num: 100_200_300, exp: "one zero zero two zero zero three zero zero"},
		{num: 126_490_799, exp: "one two six four nine zero seven nine nine"},
		{num: 1_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero"},
		{num: 9_007_912_442, exp: "nine zero zero seven nine one two four four two"},
		{num: 10_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero"},
		{num: 10_000_000_030, exp: "one zero zero zero zero zero zero zero zero three zero"},
		{num: 10_000_030_000, exp: "one zero zero zero zero zero three zero zero zero zero"},
		{num: 64_127_772_414, exp: "six four one two seven seven seven two four one four"},
		{num: 100_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 759_528_730_112, exp: "seven five nine five two eight seven three zero one one two"},
		{num: 1_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 9_515_965_217_456, exp: "nine five one five nine six five two one seven four five six"},
		{num: 10_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 50_558_442_088_500, exp: "five zero five five eight four four two zero eight eight five zero zero"},
		{num: 100_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 875_545_170_963_847, exp: "eight seven five five four five one seven zero nine six three eight four seven"},
		{num: 1_000_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 1_459_010_276_579_858, exp: "one four five nine zero one zero two seven six five seven nine eight five eight"},
		{num: 10_000_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 63_817_328_483_963_713, exp: "six three eight one seven three two eight four eight three nine six three seven one three"},
		{num: 100_000_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 503_030_044_673_410_914, exp: "five zero three zero three zero zero four four six seven three four one zero nine one four"},
		{num: 1_000_000_000_000_000_000, exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: 1_002_003_004_005_006_007, exp: "one zero zero two zero zero three zero zero four zero zero five zero zero six zero zero seven"},
		{num: 6_095_934_577_086_450_739, exp: "six zero nine five nine three four five seven seven zero eight six four five zero seven three nine"},
		{num: 126, exp: "one two six"},
		{num: 127, exp: "one two seven"},
		{num: 128, exp: "one two eight"},
		{num: 254, exp: "two five four"},
		{num: 255, exp: "two five five"},
		{num: 256, exp: "two five six"},
		{num: 32_766, exp: "three two seven six six"},
		{num: 32_767, exp: "three two seven six seven"},
		{num: 32_768, exp: "three two seven six eight"},
		{num: 65_534, exp: "six five five three four"},
		{num: 65_535, exp: "six five five three five"},
		{num: 65_536, exp: "six five five three six"},
		{num: 2_147_483_646, exp: "two one four seven four eight three six four six"},
		{num: 2_147_483_647, exp: "two one four seven four eight three six four seven"},
		{num: 2_147_483_648, exp: "two one four seven four eight three six four eight"},
		{num: 4_294_967_294, exp: "four two nine four nine six seven two nine four"},
		{num: 4_294_967_295, exp: "four two nine four nine six seven two nine five"},
		{num: 4_294_967_296, exp: "four two nine four nine six seven two nine six"},
		{num: 9_223_372_036_854_775_806, exp: "nine two two three three seven two zero three six eight five four seven seven five eight zero six"},
		{num: 9_223_372_036_854_775_807, exp: "nine two two three three seven two zero three six eight five four seven seven five eight zero seven"},
		{num: 9_223_372_036_854_775_808, exp: "nine two two three three seven two zero three six eight five four seven seven five eight zero eight"},
		{num: 18_446_744_073_709_551_614, exp: "one eight four four six seven four four zero seven three seven zero nine five five one six one four"},
		{num: 18_446_744_073_709_551_615, exp: "one eight four four six seven four four zero seven three seven zero nine five five one six one five"},
	}

	for _, tc := range tests {
		t.Run(fmt.Sprintf("%d", tc.num), func(t *testing.T) {
			var act string
			testFunc := func() {
				act = UintToDigits(tc.num)
			}
			require.NotPanics(t, testFunc, "UintToDigits(%d)", tc.num)
			assert.Equal(t, tc.exp, act, "UintToDigits(%d)", tc.num)
		})
	}
}

func TestStringToDigits(t *testing.T) {
	tests := []struct {
		num string
		exp string
	}{
		{num: "0", exp: "zero"},
		{num: "1", exp: "one"},
		{num: "-1", exp: "negative one"},
		{num: "2", exp: "two"},
		{num: "-2", exp: "negative two"},
		{num: "3", exp: "three"},
		{num: "-3", exp: "negative three"},
		{num: "4", exp: "four"},
		{num: "-4", exp: "negative four"},
		{num: "5", exp: "five"},
		{num: "-5", exp: "negative five"},
		{num: "6", exp: "six"},
		{num: "-6", exp: "negative six"},
		{num: "7", exp: "seven"},
		{num: "-7", exp: "negative seven"},
		{num: "8", exp: "eight"},
		{num: "-8", exp: "negative eight"},
		{num: "9", exp: "nine"},
		{num: "-9", exp: "negative nine"},
		{num: "10", exp: "one zero"},
		{num: "-10", exp: "negative one zero"},
		{num: "11", exp: "one one"},
		{num: "-11", exp: "negative one one"},
		{num: "12", exp: "one two"},
		{num: "-12", exp: "negative one two"},
		{num: "13", exp: "one three"},
		{num: "-13", exp: "negative one three"},
		{num: "14", exp: "one four"},
		{num: "-14", exp: "negative one four"},
		{num: "15", exp: "one five"},
		{num: "-15", exp: "negative one five"},
		{num: "16", exp: "one six"},
		{num: "-16", exp: "negative one six"},
		{num: "17", exp: "one seven"},
		{num: "-17", exp: "negative one seven"},
		{num: "18", exp: "one eight"},
		{num: "-18", exp: "negative one eight"},
		{num: "19", exp: "one nine"},
		{num: "-19", exp: "negative one nine"},
		{num: "20", exp: "two zero"},
		{num: "-20", exp: "negative two zero"},
		{num: "21", exp: "two one"},
		{num: "-21", exp: "negative two one"},
		{num: "22", exp: "two two"},
		{num: "-22", exp: "negative two two"},
		{num: "23", exp: "two three"},
		{num: "-23", exp: "negative two three"},
		{num: "24", exp: "two four"},
		{num: "-24", exp: "negative two four"},
		{num: "25", exp: "two five"},
		{num: "-25", exp: "negative two five"},
		{num: "26", exp: "two six"},
		{num: "-26", exp: "negative two six"},
		{num: "27", exp: "two seven"},
		{num: "-27", exp: "negative two seven"},
		{num: "28", exp: "two eight"},
		{num: "-28", exp: "negative two eight"},
		{num: "29", exp: "two nine"},
		{num: "-29", exp: "negative two nine"},
		{num: "30", exp: "three zero"},
		{num: "-30", exp: "negative three zero"},
		{num: "31", exp: "three one"},
		{num: "-31", exp: "negative three one"},
		{num: "32", exp: "three two"},
		{num: "-32", exp: "negative three two"},
		{num: "33", exp: "three three"},
		{num: "-33", exp: "negative three three"},
		{num: "34", exp: "three four"},
		{num: "-34", exp: "negative three four"},
		{num: "35", exp: "three five"},
		{num: "-35", exp: "negative three five"},
		{num: "36", exp: "three six"},
		{num: "-36", exp: "negative three six"},
		{num: "37", exp: "three seven"},
		{num: "-37", exp: "negative three seven"},
		{num: "38", exp: "three eight"},
		{num: "-38", exp: "negative three eight"},
		{num: "39", exp: "three nine"},
		{num: "-39", exp: "negative three nine"},
		{num: "40", exp: "four zero"},
		{num: "-40", exp: "negative four zero"},
		{num: "41", exp: "four one"},
		{num: "-41", exp: "negative four one"},
		{num: "42", exp: "four two"},
		{num: "-42", exp: "negative four two"},
		{num: "43", exp: "four three"},
		{num: "-43", exp: "negative four three"},
		{num: "44", exp: "four four"},
		{num: "-44", exp: "negative four four"},
		{num: "45", exp: "four five"},
		{num: "-45", exp: "negative four five"},
		{num: "46", exp: "four six"},
		{num: "-46", exp: "negative four six"},
		{num: "47", exp: "four seven"},
		{num: "-47", exp: "negative four seven"},
		{num: "48", exp: "four eight"},
		{num: "-48", exp: "negative four eight"},
		{num: "49", exp: "four nine"},
		{num: "-49", exp: "negative four nine"},
		{num: "50", exp: "five zero"},
		{num: "-50", exp: "negative five zero"},
		{num: "51", exp: "five one"},
		{num: "-51", exp: "negative five one"},
		{num: "52", exp: "five two"},
		{num: "-52", exp: "negative five two"},
		{num: "53", exp: "five three"},
		{num: "-53", exp: "negative five three"},
		{num: "54", exp: "five four"},
		{num: "-54", exp: "negative five four"},
		{num: "55", exp: "five five"},
		{num: "-55", exp: "negative five five"},
		{num: "56", exp: "five six"},
		{num: "-56", exp: "negative five six"},
		{num: "57", exp: "five seven"},
		{num: "-57", exp: "negative five seven"},
		{num: "58", exp: "five eight"},
		{num: "-58", exp: "negative five eight"},
		{num: "59", exp: "five nine"},
		{num: "-59", exp: "negative five nine"},
		{num: "60", exp: "six zero"},
		{num: "-60", exp: "negative six zero"},
		{num: "61", exp: "six one"},
		{num: "-61", exp: "negative six one"},
		{num: "62", exp: "six two"},
		{num: "-62", exp: "negative six two"},
		{num: "63", exp: "six three"},
		{num: "-63", exp: "negative six three"},
		{num: "64", exp: "six four"},
		{num: "-64", exp: "negative six four"},
		{num: "65", exp: "six five"},
		{num: "-65", exp: "negative six five"},
		{num: "66", exp: "six six"},
		{num: "-66", exp: "negative six six"},
		{num: "67", exp: "six seven"},
		{num: "-67", exp: "negative six seven"},
		{num: "68", exp: "six eight"},
		{num: "-68", exp: "negative six eight"},
		{num: "69", exp: "six nine"},
		{num: "-69", exp: "negative six nine"},
		{num: "70", exp: "seven zero"},
		{num: "-70", exp: "negative seven zero"},
		{num: "71", exp: "seven one"},
		{num: "-71", exp: "negative seven one"},
		{num: "72", exp: "seven two"},
		{num: "-72", exp: "negative seven two"},
		{num: "73", exp: "seven three"},
		{num: "-73", exp: "negative seven three"},
		{num: "74", exp: "seven four"},
		{num: "-74", exp: "negative seven four"},
		{num: "75", exp: "seven five"},
		{num: "-75", exp: "negative seven five"},
		{num: "76", exp: "seven six"},
		{num: "-76", exp: "negative seven six"},
		{num: "77", exp: "seven seven"},
		{num: "-77", exp: "negative seven seven"},
		{num: "78", exp: "seven eight"},
		{num: "-78", exp: "negative seven eight"},
		{num: "79", exp: "seven nine"},
		{num: "-79", exp: "negative seven nine"},
		{num: "80", exp: "eight zero"},
		{num: "-80", exp: "negative eight zero"},
		{num: "81", exp: "eight one"},
		{num: "-81", exp: "negative eight one"},
		{num: "82", exp: "eight two"},
		{num: "-82", exp: "negative eight two"},
		{num: "83", exp: "eight three"},
		{num: "-83", exp: "negative eight three"},
		{num: "84", exp: "eight four"},
		{num: "-84", exp: "negative eight four"},
		{num: "85", exp: "eight five"},
		{num: "-85", exp: "negative eight five"},
		{num: "86", exp: "eight six"},
		{num: "-86", exp: "negative eight six"},
		{num: "87", exp: "eight seven"},
		{num: "-87", exp: "negative eight seven"},
		{num: "88", exp: "eight eight"},
		{num: "-88", exp: "negative eight eight"},
		{num: "89", exp: "eight nine"},
		{num: "-89", exp: "negative eight nine"},
		{num: "90", exp: "nine zero"},
		{num: "-90", exp: "negative nine zero"},
		{num: "91", exp: "nine one"},
		{num: "-91", exp: "negative nine one"},
		{num: "92", exp: "nine two"},
		{num: "-92", exp: "negative nine two"},
		{num: "93", exp: "nine three"},
		{num: "-93", exp: "negative nine three"},
		{num: "94", exp: "nine four"},
		{num: "-94", exp: "negative nine four"},
		{num: "95", exp: "nine five"},
		{num: "-95", exp: "negative nine five"},
		{num: "96", exp: "nine six"},
		{num: "-96", exp: "negative nine six"},
		{num: "97", exp: "nine seven"},
		{num: "-97", exp: "negative nine seven"},
		{num: "98", exp: "nine eight"},
		{num: "-98", exp: "negative nine eight"},
		{num: "99", exp: "nine nine"},
		{num: "-99", exp: "negative nine nine"},
		{num: "100", exp: "one zero zero"},
		{num: "-100", exp: "negative one zero zero"},
		{num: "111", exp: "one one one"},
		{num: "-111", exp: "negative one one one"},
		{num: "54321", exp: "five four three two one"},
		{num: "-54321", exp: "negative five four three two one"},
		{num: "1234", exp: "one two three four"},
		{num: "-1234", exp: "negative one two three four"},
		{num: "1000", exp: "one zero zero zero"},
		{num: "-1000", exp: "negative one zero zero zero"},
		{num: "1001", exp: "one zero zero one"},
		{num: "-1001", exp: "negative one zero zero one"},
		{num: "1020", exp: "one zero two zero"},
		{num: "-1020", exp: "negative one zero two zero"},
		{num: "1300", exp: "one three zero zero"},
		{num: "-1300", exp: "negative one three zero zero"},
		{num: "1045", exp: "one zero four five"},
		{num: "-1045", exp: "negative one zero four five"},
		{num: "1670", exp: "one six seven zero"},
		{num: "-1670", exp: "negative one six seven zero"},
		{num: "1809", exp: "one eight zero nine"},
		{num: "-1809", exp: "negative one eight zero nine"},
		{num: "2000", exp: "two zero zero zero"},
		{num: "-2000", exp: "negative two zero zero zero"},
		{num: "2001", exp: "two zero zero one"},
		{num: "-2001", exp: "negative two zero zero one"},
		{num: "2020", exp: "two zero two zero"},
		{num: "-2020", exp: "negative two zero two zero"},
		{num: "2300", exp: "two three zero zero"},
		{num: "-2300", exp: "negative two three zero zero"},
		{num: "2045", exp: "two zero four five"},
		{num: "-2045", exp: "negative two zero four five"},
		{num: "2670", exp: "two six seven zero"},
		{num: "-2670", exp: "negative two six seven zero"},
		{num: "2809", exp: "two eight zero nine"},
		{num: "-2809", exp: "negative two eight zero nine"},
		{num: "3000", exp: "three zero zero zero"},
		{num: "-3000", exp: "negative three zero zero zero"},
		{num: "3001", exp: "three zero zero one"},
		{num: "-3001", exp: "negative three zero zero one"},
		{num: "3020", exp: "three zero two zero"},
		{num: "-3020", exp: "negative three zero two zero"},
		{num: "3300", exp: "three three zero zero"},
		{num: "-3300", exp: "negative three three zero zero"},
		{num: "3045", exp: "three zero four five"},
		{num: "-3045", exp: "negative three zero four five"},
		{num: "3670", exp: "three six seven zero"},
		{num: "-3670", exp: "negative three six seven zero"},
		{num: "3809", exp: "three eight zero nine"},
		{num: "-3809", exp: "negative three eight zero nine"},
		{num: "4000", exp: "four zero zero zero"},
		{num: "-4000", exp: "negative four zero zero zero"},
		{num: "4001", exp: "four zero zero one"},
		{num: "-4001", exp: "negative four zero zero one"},
		{num: "4020", exp: "four zero two zero"},
		{num: "-4020", exp: "negative four zero two zero"},
		{num: "4300", exp: "four three zero zero"},
		{num: "-4300", exp: "negative four three zero zero"},
		{num: "4045", exp: "four zero four five"},
		{num: "-4045", exp: "negative four zero four five"},
		{num: "4670", exp: "four six seven zero"},
		{num: "-4670", exp: "negative four six seven zero"},
		{num: "4809", exp: "four eight zero nine"},
		{num: "-4809", exp: "negative four eight zero nine"},
		{num: "5000", exp: "five zero zero zero"},
		{num: "-5000", exp: "negative five zero zero zero"},
		{num: "5001", exp: "five zero zero one"},
		{num: "-5001", exp: "negative five zero zero one"},
		{num: "5020", exp: "five zero two zero"},
		{num: "-5020", exp: "negative five zero two zero"},
		{num: "5300", exp: "five three zero zero"},
		{num: "-5300", exp: "negative five three zero zero"},
		{num: "5045", exp: "five zero four five"},
		{num: "-5045", exp: "negative five zero four five"},
		{num: "5670", exp: "five six seven zero"},
		{num: "-5670", exp: "negative five six seven zero"},
		{num: "5809", exp: "five eight zero nine"},
		{num: "-5809", exp: "negative five eight zero nine"},
		{num: "6000", exp: "six zero zero zero"},
		{num: "-6000", exp: "negative six zero zero zero"},
		{num: "6001", exp: "six zero zero one"},
		{num: "-6001", exp: "negative six zero zero one"},
		{num: "6020", exp: "six zero two zero"},
		{num: "-6020", exp: "negative six zero two zero"},
		{num: "6300", exp: "six three zero zero"},
		{num: "-6300", exp: "negative six three zero zero"},
		{num: "6045", exp: "six zero four five"},
		{num: "-6045", exp: "negative six zero four five"},
		{num: "6670", exp: "six six seven zero"},
		{num: "-6670", exp: "negative six six seven zero"},
		{num: "6809", exp: "six eight zero nine"},
		{num: "-6809", exp: "negative six eight zero nine"},
		{num: "7000", exp: "seven zero zero zero"},
		{num: "-7000", exp: "negative seven zero zero zero"},
		{num: "7001", exp: "seven zero zero one"},
		{num: "-7001", exp: "negative seven zero zero one"},
		{num: "7020", exp: "seven zero two zero"},
		{num: "-7020", exp: "negative seven zero two zero"},
		{num: "7300", exp: "seven three zero zero"},
		{num: "-7300", exp: "negative seven three zero zero"},
		{num: "7045", exp: "seven zero four five"},
		{num: "-7045", exp: "negative seven zero four five"},
		{num: "7670", exp: "seven six seven zero"},
		{num: "-7670", exp: "negative seven six seven zero"},
		{num: "7809", exp: "seven eight zero nine"},
		{num: "-7809", exp: "negative seven eight zero nine"},
		{num: "8000", exp: "eight zero zero zero"},
		{num: "-8000", exp: "negative eight zero zero zero"},
		{num: "8001", exp: "eight zero zero one"},
		{num: "-8001", exp: "negative eight zero zero one"},
		{num: "8020", exp: "eight zero two zero"},
		{num: "-8020", exp: "negative eight zero two zero"},
		{num: "8300", exp: "eight three zero zero"},
		{num: "-8300", exp: "negative eight three zero zero"},
		{num: "8045", exp: "eight zero four five"},
		{num: "-8045", exp: "negative eight zero four five"},
		{num: "8670", exp: "eight six seven zero"},
		{num: "-8670", exp: "negative eight six seven zero"},
		{num: "8809", exp: "eight eight zero nine"},
		{num: "-8809", exp: "negative eight eight zero nine"},
		{num: "9000", exp: "nine zero zero zero"},
		{num: "-9000", exp: "negative nine zero zero zero"},
		{num: "9001", exp: "nine zero zero one"},
		{num: "-9001", exp: "negative nine zero zero one"},
		{num: "9020", exp: "nine zero two zero"},
		{num: "-9020", exp: "negative nine zero two zero"},
		{num: "9300", exp: "nine three zero zero"},
		{num: "-9300", exp: "negative nine three zero zero"},
		{num: "9045", exp: "nine zero four five"},
		{num: "-9045", exp: "negative nine zero four five"},
		{num: "9670", exp: "nine six seven zero"},
		{num: "-9670", exp: "negative nine six seven zero"},
		{num: "9809", exp: "nine eight zero nine"},
		{num: "-9809", exp: "negative nine eight zero nine"},
		{num: "9999", exp: "nine nine nine nine"},
		{num: "-9999", exp: "negative nine nine nine nine"},
		{num: "10000", exp: "one zero zero zero zero"},
		{num: "-10000", exp: "negative one zero zero zero zero"},
		{num: "24745", exp: "two four seven four five"},
		{num: "-24745", exp: "negative two four seven four five"},
		{num: "99999", exp: "nine nine nine nine nine"},
		{num: "-99999", exp: "negative nine nine nine nine nine"},
		{num: "100000", exp: "one zero zero zero zero zero"},
		{num: "-100000", exp: "negative one zero zero zero zero zero"},
		{num: "552887", exp: "five five two eight eight seven"},
		{num: "-552887", exp: "negative five five two eight eight seven"},
		{num: "1000000", exp: "one zero zero zero zero zero zero"},
		{num: "-1000000", exp: "negative one zero zero zero zero zero zero"},
		{num: "1002003", exp: "one zero zero two zero zero three"},
		{num: "-1002003", exp: "negative one zero zero two zero zero three"},
		{num: "5485065", exp: "five four eight five zero six five"},
		{num: "-5485065", exp: "negative five four eight five zero six five"},
		{num: "10000000", exp: "one zero zero zero zero zero zero zero"},
		{num: "-10000000", exp: "negative one zero zero zero zero zero zero zero"},
		{num: "82212496", exp: "eight two two one two four nine six"},
		{num: "-82212496", exp: "negative eight two two one two four nine six"},
		{num: "100000000", exp: "one zero zero zero zero zero zero zero zero"},
		{num: "-100000000", exp: "negative one zero zero zero zero zero zero zero zero"},
		{num: "100200300", exp: "one zero zero two zero zero three zero zero"},
		{num: "-100200300", exp: "negative one zero zero two zero zero three zero zero"},
		{num: "126490799", exp: "one two six four nine zero seven nine nine"},
		{num: "-126490799", exp: "negative one two six four nine zero seven nine nine"},
		{num: "1000000000", exp: "one zero zero zero zero zero zero zero zero zero"},
		{num: "-1000000000", exp: "negative one zero zero zero zero zero zero zero zero zero"},
		{num: "9007912442", exp: "nine zero zero seven nine one two four four two"},
		{num: "-9007912442", exp: "negative nine zero zero seven nine one two four four two"},
		{num: "10000000000", exp: "one zero zero zero zero zero zero zero zero zero zero"},
		{num: "-10000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero"},
		{num: "10000000030", exp: "one zero zero zero zero zero zero zero zero three zero"},
		{num: "-10000000030", exp: "negative one zero zero zero zero zero zero zero zero three zero"},
		{num: "10000030000", exp: "one zero zero zero zero zero three zero zero zero zero"},
		{num: "-10000030000", exp: "negative one zero zero zero zero zero three zero zero zero zero"},
		{num: "64127772414", exp: "six four one two seven seven seven two four one four"},
		{num: "-64127772414", exp: "negative six four one two seven seven seven two four one four"},
		{num: "100000000000", exp: "one zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "-100000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "759528730112", exp: "seven five nine five two eight seven three zero one one two"},
		{num: "-759528730112", exp: "negative seven five nine five two eight seven three zero one one two"},
		{num: "1000000000000", exp: "one zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "-1000000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "9515965217456", exp: "nine five one five nine six five two one seven four five six"},
		{num: "-9515965217456", exp: "negative nine five one five nine six five two one seven four five six"},
		{num: "10000000000000", exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "-10000000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "50558442088500", exp: "five zero five five eight four four two zero eight eight five zero zero"},
		{num: "-50558442088500", exp: "negative five zero five five eight four four two zero eight eight five zero zero"},
		{num: "100000000000000", exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "-100000000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "875545170963847", exp: "eight seven five five four five one seven zero nine six three eight four seven"},
		{num: "-875545170963847", exp: "negative eight seven five five four five one seven zero nine six three eight four seven"},
		{num: "1000000000000000", exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "-1000000000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "1459010276579858", exp: "one four five nine zero one zero two seven six five seven nine eight five eight"},
		{num: "-1459010276579858", exp: "negative one four five nine zero one zero two seven six five seven nine eight five eight"},
		{num: "10000000000000000", exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "-10000000000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "63817328483963713", exp: "six three eight one seven three two eight four eight three nine six three seven one three"},
		{num: "-63817328483963713", exp: "negative six three eight one seven three two eight four eight three nine six three seven one three"},
		{num: "100000000000000000", exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "-100000000000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "503030044673410914", exp: "five zero three zero three zero zero four four six seven three four one zero nine one four"},
		{num: "-503030044673410914", exp: "negative five zero three zero three zero zero four four six seven three four one zero nine one four"},
		{num: "1000000000000000000", exp: "one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "-1000000000000000000", exp: "negative one zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero zero"},
		{num: "1002003004005006007", exp: "one zero zero two zero zero three zero zero four zero zero five zero zero six zero zero seven"},
		{num: "-1002003004005006007", exp: "negative one zero zero two zero zero three zero zero four zero zero five zero zero six zero zero seven"},
		{num: "6095934577086450739", exp: "six zero nine five nine three four five seven seven zero eight six four five zero seven three nine"},
		{num: "-6095934577086450739", exp: "negative six zero nine five nine three four five seven seven zero eight six four five zero seven three nine"},
		{num: "126", exp: "one two six"},
		{num: "127", exp: "one two seven"},
		{num: "128", exp: "one two eight"},
		{num: "-127", exp: "negative one two seven"},
		{num: "-128", exp: "negative one two eight"},
		{num: "-129", exp: "negative one two nine"},
		{num: "254", exp: "two five four"},
		{num: "255", exp: "two five five"},
		{num: "256", exp: "two five six"},
		{num: "32766", exp: "three two seven six six"},
		{num: "32767", exp: "three two seven six seven"},
		{num: "32768", exp: "three two seven six eight"},
		{num: "-32767", exp: "negative three two seven six seven"},
		{num: "-32768", exp: "negative three two seven six eight"},
		{num: "-32769", exp: "negative three two seven six nine"},
		{num: "65534", exp: "six five five three four"},
		{num: "65535", exp: "six five five three five"},
		{num: "65536", exp: "six five five three six"},
		{num: "2147483646", exp: "two one four seven four eight three six four six"},
		{num: "2147483647", exp: "two one four seven four eight three six four seven"},
		{num: "2147483648", exp: "two one four seven four eight three six four eight"},
		{num: "-2147483647", exp: "negative two one four seven four eight three six four seven"},
		{num: "-2147483648", exp: "negative two one four seven four eight three six four eight"},
		{num: "-2147483649", exp: "negative two one four seven four eight three six four nine"},
		{num: "4294967294", exp: "four two nine four nine six seven two nine four"},
		{num: "4294967295", exp: "four two nine four nine six seven two nine five"},
		{num: "4294967296", exp: "four two nine four nine six seven two nine six"},
		{num: "9223372036854775806", exp: "nine two two three three seven two zero three six eight five four seven seven five eight zero six"},
		{num: "9223372036854775807", exp: "nine two two three three seven two zero three six eight five four seven seven five eight zero seven"},
		{num: "9223372036854775808", exp: "nine two two three three seven two zero three six eight five four seven seven five eight zero eight"},
		{num: "-9223372036854775807", exp: "negative nine two two three three seven two zero three six eight five four seven seven five eight zero seven"},
		{num: "-9223372036854775808", exp: "negative nine two two three three seven two zero three six eight five four seven seven five eight zero eight"},
		{num: "-9223372036854775809", exp: "negative nine two two three three seven two zero three six eight five four seven seven five eight zero nine"},
		{num: "29055283352890193685114459552078471644701080980",
			exp: "two nine zero five five two eight three three five two " +
				"eight nine zero one nine three six eight five one one four " +
				"four five nine five five two zero seven eight four seven one " +
				"six four four seven zero one zero eight zero nine eight zero"},
		{num: "-29055283352890193685114459552078471644701080980",
			exp: "negative two nine zero five five two eight three three five two " +
				"eight nine zero one nine three six eight five one one four " +
				"four five nine five five two zero seven eight four seven one " +
				"six four four seven zero one zero eight zero nine eight zero"},
		{num: "999999999999999999999999999999999999999999999999",
			exp: "nine nine nine nine nine nine nine nine nine nine nine nine " +
				"nine nine nine nine nine nine nine nine nine nine nine nine " +
				"nine nine nine nine nine nine nine nine nine nine nine nine " +
				"nine nine nine nine nine nine nine nine nine nine nine nine"},
		{num: "-999999999999999999999999999999999999999999999999",
			exp: "negative nine nine nine nine nine nine nine nine nine nine nine nine " +
				"nine nine nine nine nine nine nine nine nine nine nine nine " +
				"nine nine nine nine nine nine nine nine nine nine nine nine " +
				"nine nine nine nine nine nine nine nine nine nine nine nine"},
		{num: "99 bananas", exp: "nine nine bananas"},
		{num: "99bananas", exp: "nine nine bananas"},
		{num: "99  bananas", exp: "nine nine  bananas"},
		{num: "3.141", exp: "three point one four one"},
		{num: "-6.282", exp: "negative six point two eight two"},
		{num: ".771", exp: "point seven seven one"},
		{num: "-.801", exp: "negative point eight zero one"},
	}

	for _, tc := range tests {
		t.Run(tc.num, func(t *testing.T) {
			var act string
			testFunc := func() {
				act = StringToDigits(tc.num)
			}
			require.NotPanics(t, testFunc, "StringToDigits(%d)", tc.num)
			assert.Equal(t, tc.exp, act, "StringToDigits(%d)", tc.num)
		})
	}
}
